CREATE DATABASE OLA ;

USE OLA ;

CREATE TABLE DRIVER
(
DRIVER_IDD INT PRIMARY KEY,
DRIVER_NAME VARCHAR(78),
DRIVER_PICKUP VARCHAR(67),
DRIVER_DROPOFF VARCHAR(65),
DRIVER_FARE INT
) ;

ALTER TABLE DRIVER ADD COLUMN SALARY INT AFTER DRIVER_FARE ;

INSERT INTO DRIVER VALUES ("1","RADHE","VASTRAL","MANINAGAR","65","10000");
INSERT INTO DRIVER VALUES ("2","JOY","VASTRA","NAGAR","27","1110000");
INSERT INTO DRIVER VALUES ("3","SHYAM","DARIYAPUR","SULTANPUR","70","20000");
INSERT INTO DRIVER VALUES ("4","SAHAY","SAHIBAUGH","GANDHINAGAR","80","30000");
INSERT INTO DRIVER VALUES ("5","MUNNA","CHARBAUGH","AALAMBAUGH","90","40000");
INSERT INTO DRIVER VALUES ("6","RAJU","KNIT","KNITM","110","50000");
INSERT INTO DRIVER VALUES ("7","KEWAL","CHAROD","ROADIYE","115","60000");
INSERT INTO DRIVER VALUES ("8","JIGNESH","CIVIL","ANAND","125","70000");
INSERT INTO DRIVER VALUES ("9","JAY","CPROAD","CGROAD","130","80000");
INSERT INTO DRIVER VALUES ("10","RAJESH","NIRANT","RABARI","150","90000");
INSERT INTO DRIVER VALUES ("11","RITIK","APPAREL","AMARIWADI","50","100000");
INSERT INTO DRIVER VALUES ("12","RIYAAN","JAMNAGAR","RAJKOT","35","11000");
INSERT INTO DRIVER VALUES ("13","RIYA","JAMNA","RAJA","55","15000");
INSERT INTO DRIVER VALUES ("14","JIYA","SAHDOL","GOA","58","45000");
INSERT INTO DRIVER VALUES ("15","MEESHU","LAPATA","RANINAGAR","17","5634");
INSERT INTO DRIVER VALUES ("16","KRISH","RAMGANJ","RAJ","18", "4532");
INSERT INTO DRIVER VALUES ("17","JENNY","NIRAALA","PUNE","20", "2678");
INSERT INTO DRIVER VALUES ("18","KUSH","CHAURAHA","KUDAIL","25", "9999");
INSERT INTO DRIVER VALUES ("19","EPPY","KAMTAGANJ","JAMNAGAR","35", "1011");
INSERT INTO DRIVER VALUES ("20","KRISHH","RAMAGANJ","JAKOT","40", "4765");

SELECT * FROM DRIVER ;

UPDATE DRIVER SET DRIVER_FARE = 55 WHERE DRIVER_IDD = 2 ;


CREATE TABLE PASSENGER
(
PASSENGER_ID INT PRIMARY KEY,
PASSENGER_NAME VARCHAR(78),
PASSENGER_GENDER ENUM("M","F"),
PA_VEHICLE ENUM("AVAILABLE","CANCELLED","RESERVED"),
P_AGE INT ,
FOREIGN KEY(P_AGE) REFERENCES DRIVER (DRIVER_IDD) 
);

DESCRIBE PASSENGER ;

INSERT INTO PASSENGER VALUES("101", "SINGH", "M", "CANCELLED","1");
INSERT  INTO PASSENGER VALUES("102","AJAY", "M","RESERVED","2");
INSERT INTO PASSENGER VALUES("103","NEHA", "F","AVAILABLE","3");
INSERT INTO PASSENGER VALUES("104","VIJAY", "M","CANCELLED","4");
INSERT INTO PASSENGER VALUES("105","JOY", "M","CANCELLED","5");
INSERT INTO PASSENGER VALUES("106","NISHA", "F","CANCELLED","6");
INSERT INTO PASSENGER VALUES("107","VARTIKA", "F","CANCELLED","7");
INSERT INTO PASSENGER VALUES("108","VANJAY", "M","CANCELLED","8");
INSERT INTO PASSENGER VALUES("109","KULBHUSHAN", "M","CANCELLED","9");
INSERT INTO PASSENGER VALUES("110","PARUL", "F","CANCELLED","10");
INSERT INTO PASSENGER VALUES("111","VINEETA", "F","CANCELLED", "11");
INSERT INTO PASSENGER VALUES("112","SUNEETA", "F","RESERVED", "12");
INSERT INTO PASSENGER VALUES("113","ABHISHEK", "M","AVAILABLE", "13");
INSERT INTO PASSENGER VALUES("114","SHRADDHA", "F","RESERVED","14");
INSERT INTO PASSENGER VALUES("115","KRISHNA", "M","CANCELLED","15");
INSERT INTO PASSENGER VALUES("116","RAMAN", "M","RESERVED","16");
INSERT INTO PASSENGER VALUES("117","SUHANSHI", "F","CANCELLED","17");
INSERT INTO PASSENGER VALUES("118","SNEHA", "F","RESERVED","18");
INSERT INTO PASSENGER VALUES("119","POOJA", "F","AVAILABLE","19");
INSERT INTO PASSENGER VALUES("120","FAIZ", "M","CANCELLED","20");


SELECT * FROM PASSENGER ;

SELECT * FROM PASSENGER WHERE PASSENGER_NAME = "SINGH" ;

SELECT * FROM PASSENGER WHERE P_AGE = 5 AND PASSENGER_ID = 105 ;

SELECT DISTINCT PASSENGER_NAME FROM PASSENGER ;

SELECT * FROM DRIVER WHERE DRIVER_NAME = 'JOY' AND DRIVER_IDD = '2';

SELECT * FROM DRIVER WHERE DRIVER_NAME = 'MUNNA'OR DRIVER_IDD = '6' ;

SELECT * FROM DRIVER WHERE NOT (DRIVER_NAME = 'MUNNA' OR DRIVER_IDD = '6');

SELECT * FROM PASSENGER WHERE P_AGE ORDER BY P_AGE
DESC ;

SELECT * FROM DRIVER LIMIT 5 ;

SELECT MAX( DRIVER_FARE)  FROM DRIVER ;

SELECT MIN(DRIVER_FARE) FROM DRIVER ;

SELECT AVG(DRIVER_FARE) FROM DRIVER ;

SELECT * FROM PASSENGER WHERE PASSENGER_NAME LIKE "S%" ;

SELECT * FROM PASSENGER WHERE PASSENGER_NAME LIKE "%GH%";

SELECT * FROM PASSENGER WHERE PASSENGER_NAME LIKE "___Y" ;

SELECT * FROM PASSENGER WHERE PASSENGER_NAME BETWEEN "V" AND "Y" ;

SELECT PASSENGER_NAME AS PANAME, PASSENGER_GENDER AS PGENDER,
PA_VEHICLE AS PAVE FROM PASSENGER ;

SELECT DRIVER_FARE , COUNT(DRIVER_IDD) FROM DRIVER 
GROUP BY DRIVER_FARE ;

SELECT DRIVER_IDD , COUNT(SALARY) FROM DRIVER 
GROUP BY DRIVER_IDD HAVING COUNT(SALARY) > 10000;

SELECT * FROM PASSENGER ;

SELECT PASSENGER_ID, PASSENGER_NAME ,P_AGE,
CASE
WHEN P_AGE > 18 THEN "ALLOWED FOR SITTING..."
WHEN P_AGE = 18 THEN "WELCOME FOR SITTING..."
ELSE "NOT ALLOWED"
END AS "GHGH"
FROM PASSENGER ;

SELECT * FROM DRIVER ;

ALTER TABLE DRIVER DROP COLUMN DATE ;

SELECT DRIVER_PICKUP , DRIVER_NAME , REVERSE(DRIVER_PICKUP)
FROM DRIVER ;

SELECT * FROM PASSENGER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, LENGTH(DRIVER_DROPOFF) FROM
DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, LPAD(DRIVER_NAME ,10, "-")
FROM DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, RPAD(DRIVER_NAME ,10, "-")
FROM DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, LCASE(DRIVER_NAME)
FROM DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, INSTR(DRIVER_NAME, "F")
FROM DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, 
CONCAT(DRIVER_NAME , "/" ,DRIVER_DROPOFF) FROM DRIVER ;

SELECT DRIVER_NAME ,DRIVER_DROPOFF, DRIVER_FARE, 
CONCAT_WS("-",  DRIVER_NAME ,DRIVER_DROPOFF) FROM DRIVER ;

SELECT * FROM DRIVER 
INNER JOIN PASSENGER 
ON DRIVER.DRIVER_IDD = PASSENGER.P_AGE ;

SELECT * FROM DRIVER
RIGHT JOIN PASSENGER 
ON DRIVER.DRIVER_IDD = PASSENGER.P_AGE ;

SELECT * FROM DRIVER
LEFT JOIN PASSENGER 
ON DRIVER.DRIVER_IDD = PASSENGER.P_AGE ;

SELECT * FROM DRIVER CROSS JOIN PASSENGER ;





